/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import Controller.EmployeeController;

/**
 *
 * @author ester
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainMenuLabel = new javax.swing.JLabel();
        jActualizarButton = new javax.swing.JButton();
        jIngresarButton = new javax.swing.JButton();
        jListarButton = new javax.swing.JButton();
        jBorrarButton = new javax.swing.JButton();
        jSalirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMainMenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainMenuLabel.setText("Gestion de Empleados");

        jActualizarButton.setText("Actualizar Empleado");
        jActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarButtonActionPerformed(evt);
            }
        });

        jIngresarButton.setText("Ingresar Empleado");
        jIngresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarButtonActionPerformed(evt);
            }
        });

        jListarButton.setText("Listar Empleado");
        jListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarButtonActionPerformed(evt);
            }
        });

        jBorrarButton.setText("Borrar Empleado");
        jBorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarButtonActionPerformed(evt);
            }
        });

        jSalirButton.setText("Salir");
        jSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jListarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jIngresarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jActualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBorrarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSalirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMainMenuLabel)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jIngresarButton)
                .addGap(18, 18, 18)
                .addComponent(jActualizarButton)
                .addGap(18, 18, 18)
                .addComponent(jListarButton)
                .addGap(18, 18, 18)
                .addComponent(jBorrarButton)
                .addGap(18, 18, 18)
                .addComponent(jSalirButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarButtonActionPerformed
        jActualizarButton.addActionListener(e -> EmployeeController.bbdd.actualizarEmpleado());
    }//GEN-LAST:event_jActualizarButtonActionPerformed

    private void jListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarButtonActionPerformed
        jListarButton.addActionListener(e -> EmployeeController.bbdd.listarEmpleados());
    }//GEN-LAST:event_jListarButtonActionPerformed

    private void jBorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarButtonActionPerformed
        jBorrarButton.addActionListener(e -> EmployeeController.bbdd.borrarEmpleado());
    }//GEN-LAST:event_jBorrarButtonActionPerformed

    private void jSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirButtonActionPerformed

    private void jIngresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarButtonActionPerformed
        jIngresarButton.addActionListener(e -> EmployeeController.bbdd.ingresarEmpleado());

    }//GEN-LAST:event_jIngresarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jActualizarButton;
    private javax.swing.JButton jBorrarButton;
    private javax.swing.JButton jIngresarButton;
    private javax.swing.JButton jListarButton;
    private javax.swing.JLabel jMainMenuLabel;
    private javax.swing.JButton jSalirButton;
    // End of variables declaration//GEN-END:variables
}
